spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanghaero
    username: root
    password: Rkdalsqja1!
    hikari:
      maximum-pool-size: 20